# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  # Clear finished Solid Queue jobs
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  
  # Process daily job alerts every day at 8 AM
  daily_job_alerts:
    class: DailyJobAlertsJob
    queue: default
    schedule: every day at 8am
  
  # Process weekly job alerts every Monday at 9 AM
  weekly_job_alerts:
    class: WeeklyJobAlertsJob
    queue: default
    schedule: every Monday at 9am

development:
  # For development, run job alerts less frequently for testing
  test_job_alerts:
    class: BulkJobAlertsJob
    queue: default
    schedule: every 5 minutes
